"""Database component — shared Aurora Serverless v2, Valkey Serverless, DynamoDB.

All three resources are shared across every tenant.  Per-tenant isolation is
achieved at the database/user/key-prefix level, not the resource level.
"""

from typing import Optional

from aws_cdk import Duration, RemovalPolicy, Stack
from aws_cdk import aws_dynamodb as dynamodb
from aws_cdk import aws_ec2 as ec2
from aws_cdk import aws_elasticache as elasticache
from aws_cdk import aws_kms as kms
from aws_cdk import aws_logs as logs
from aws_cdk import aws_rds as rds
from aws_cdk import aws_secretsmanager as secretsmanager
from aws_cdk import aws_ssm as ssm
from cdk_nag import NagSuppressions
from constructs import Construct

from ..constants import (
    AURORA_ENGINE_VERSION,
    AURORA_MAX_ACU,
    AURORA_MIN_ACU,
    MYSQL_PORT,
    SSM_AURORA_ENDPOINT,
    SSM_AURORA_SECRET_ARN,
    VALKEY_PORT,
)


class DatabaseComponents:
    """Creates the shared Aurora cluster, Valkey cache, and tenant DynamoDB table.

    Build order (called from SharedInfraStack.__init__):
      1. create_aurora(vpc, aurora_sg, kms_key)
      2. create_valkey(vpc, valkey_sg, kms_key)
      3. create_tenant_registry(kms_key)
    """

    def __init__(self, scope: Construct) -> None:
        self.scope = scope

        # Set by create_aurora()
        self.aurora_cluster:      Optional[rds.DatabaseCluster] = None
        self.aurora_admin_secret: Optional[secretsmanager.Secret] = None

        # Set by create_valkey()
        self.valkey_cache: Optional[elasticache.CfnServerlessCache] = None

        # Set by create_tenant_registry()
        self.tenant_table: Optional[dynamodb.Table] = None

    # ── Aurora Serverless v2 ──────────────────────────────────────────────────

    def create_aurora(
        self,
        vpc: ec2.Vpc,
        aurora_sg: ec2.SecurityGroup,
        kms_key: kms.Key,
    ) -> tuple[rds.DatabaseCluster, secretsmanager.ISecret]:
        """Create the shared Aurora MySQL Serverless v2 cluster.

        Architecture:
            1 writer + 1 reader instance, both Serverless v2.  The reader
            provides read scaling and multi-AZ failover capability.

        Scaling:
            Min: AURORA_MIN_ACU (0.5 ACU — scales to near-zero when idle)
            Max: AURORA_MAX_ACU (32 ACU — roughly 2x r6g.large)

        Admin credentials:
            Generated by CDK, KMS-encrypted, stored in Secrets Manager.
            Unsafe punctuation chars excluded to avoid MySQL CLI quoting issues.
            The ARN is stored in SSM for the provisioner Lambda to look up.

        Removal policy:
            RETAIN + deletion_protection=True (HIPAA: never auto-drop patient data).
            To destroy during sprint testing:
              1. aws rds modify-db-cluster --db-cluster-identifier <id>
                     --no-deletion-protection
              2. Remove the cluster manually or set removal_policy=DESTROY.

        CloudWatch log exports:
            error, general, slowquery — retained 1 year.

        Automated backups:
            35-day retention (maximum Aurora supports).
            Supplemented by 7-year AWS Backup plan in TenantStack for HIPAA.

        Returns:
            (cluster, admin_secret) tuple.
        """
        # ---- Parameter group -------------------------------------------------
        # require_secure_transport=ON: force TLS for all connections.
        # slow_query_log + general_log ship to CloudWatch for HIPAA audit trail.
        engine = rds.DatabaseClusterEngine.aurora_mysql(version=AURORA_ENGINE_VERSION)

        param_group = rds.ParameterGroup(
            self.scope,
            "AuroraParamGroup",
            engine=engine,
            description="Tarevo shared Aurora MySQL — secure transport + query logging",
            parameters={
                "require_secure_transport": "ON",
                "slow_query_log":           "1",
                "long_query_time":          "2",   # log queries slower than 2 s
                "general_log":             "1",
                "log_output":              "FILE", # route logs to CloudWatch
            },
        )

        # ---- Aurora Serverless v2 cluster ------------------------------------
        cluster = rds.DatabaseCluster(
            self.scope,
            "AuroraCluster",
            engine=engine,
            credentials=rds.Credentials.from_generated_secret(
                "admin",
                encryption_key=kms_key,
                # Exclude chars that break MySQL CLI quoting or shell interpolation
                exclude_characters=" %+~`#$&*()|[]{}:;<>?!'/@\"\\",
            ),
            writer=rds.ClusterInstance.serverless_v2("writer"),
            readers=[
                # scale_with_writer=True keeps the reader in promotion tier 0
                # so it can participate in failover and scales with the writer.
                rds.ClusterInstance.serverless_v2("reader", scale_with_writer=True)
            ],
            serverless_v2_min_capacity=AURORA_MIN_ACU,
            serverless_v2_max_capacity=AURORA_MAX_ACU,
            vpc=vpc,
            vpc_subnets=ec2.SubnetSelection(
                subnet_type=ec2.SubnetType.PRIVATE_WITH_EGRESS
            ),
            security_groups=[aurora_sg],
            parameter_group=param_group,
            storage_encrypted=True,
            storage_encryption_key=kms_key,
            deletion_protection=True,
            removal_policy=RemovalPolicy.RETAIN,
            backup=rds.BackupProps(
                retention=Duration.days(35),
                preferred_window="03:00-04:00",
            ),
            cloudwatch_logs_exports=["error", "general", "slowquery"],
            cloudwatch_logs_retention=logs.RetentionDays.ONE_YEAR,
            port=MYSQL_PORT,
        )

        admin_secret = cluster.secret
        assert admin_secret is not None, "CDK should generate a secret via from_generated_secret"

        # ---- SSM exports -----------------------------------------------------
        # TenantStack and the provisioner Lambda read these at deploy time.
        ssm.StringParameter(
            self.scope,
            "AuroraEndpointParam",
            parameter_name=SSM_AURORA_ENDPOINT,
            string_value=cluster.cluster_endpoint.hostname,
            description="Aurora Serverless v2 writer endpoint hostname",
        )

        ssm.StringParameter(
            self.scope,
            "AuroraSecretArnParam",
            parameter_name=SSM_AURORA_SECRET_ARN,
            string_value=admin_secret.secret_arn,
            description="Aurora admin credentials secret ARN",
        )

        # ---- Nag suppressions -----------------------------------------------
        NagSuppressions.add_resource_suppressions(
            cluster,
            [
                {
                    "id": "AwsSolutions-RDS6",
                    "reason": (
                        "IAM database authentication is not used.  The multi-tenant "
                        "architecture uses per-tenant MySQL users (password via "
                        "Secrets Manager) rather than IAM roles, which simplifies "
                        "the provisioner Lambda and avoids per-tenant IAM plumbing."
                    ),
                },
                {
                    "id": "AwsSolutions-RDS10",
                    "reason": "deletion_protection=True IS set on this cluster.",
                },
                {
                    "id": "AwsSolutions-RDS11",
                    "reason": (
                        "OpenEMR requires the standard MySQL port 3306.  "
                        "The cluster is in private subnets with a restrictive "
                        "security group; port obfuscation adds negligible security "
                        "benefit in this architecture."
                    ),
                },
                {
                    "id": "AwsSolutions-RDS14",
                    "reason": (
                        "Aurora Serverless v2 does not support backtrack. "
                        "Point-in-time recovery and 35-day automated backups "
                        "provide the equivalent protection."
                    ),
                },
                {
                    "id": "HIPAA.Security-AuroraMySQLBacktracking",
                    "reason": "Aurora Serverless v2 does not support backtrack (AWS constraint).",
                },
                {
                    "id": "HIPAA.Security-RDSInBackupPlan",
                    "reason": (
                        "Aurora has 35-day automated backups enabled.  Long-term "
                        "7-year retention is handled by the AWS Backup plan in "
                        "TenantStack (Sprint 4.12)."
                    ),
                },
                {
                    "id": "HIPAA.Security-RDSLoggingEnabled",
                    "reason": (
                        "error, general, and slowquery logs are exported to CloudWatch. "
                        "The MariaDB Audit Plugin (server_audit_*) is required for "
                        "the 'audit' log export on Aurora MySQL Serverless v2 and "
                        "will be configured in a follow-up sprint."
                    ),
                    "appliesTo": ["LogExport::audit"],
                },
                {
                    "id": "HIPAA.Security-RDSMultiAZSupport",
                    "reason": (
                        "Aurora Serverless v2 writer + reader spans two AZs, "
                        "providing multi-AZ failover capability equivalent to Multi-AZ."
                    ),
                },
                {
                    "id": "HIPAA.Security-RDSEnhancedMonitoringEnabled",
                    "reason": (
                        "Enhanced monitoring for Aurora Serverless v2 instances is "
                        "managed at the cluster level via CloudWatch metrics. "
                        "Instance-level OS monitoring is not configurable on "
                        "Serverless v2 compute (AWS constraint)."
                    ),
                },
            ],
            apply_to_children=True,  # covers writer, reader, subnet group
        )

        # The generated secret lives at AuroraCluster/Secret/Resource — use
        # path-based suppression because cluster.secret is an ISecret interface
        # (not a concrete Construct) and add_resource_suppressions won't resolve it.
        stack = Stack.of(self.scope)
        stack_name = stack.stack_name  # e.g. "TarevoSharedInfra"

        NagSuppressions.add_resource_suppressions_by_path(
            stack,
            f"/{stack_name}/AuroraCluster/Secret/Resource",
            [
                {
                    "id": "AwsSolutions-SMG4",
                    "reason": (
                        "Automatic rotation is not yet configured.  "
                        "Add a rotation Lambda before production launch."
                    ),
                },
                {
                    "id": "HIPAA.Security-SecretsManagerRotationEnabled",
                    "reason": (
                        "Rotation not yet configured.  "
                        "Add a rotation Lambda before production launch."
                    ),
                },
            ],
        )

        # CDK creates a singleton LogRetention Lambda at the STACK level (not
        # under the cluster) to manage CloudWatch log group retention periods.
        # Its construct ID is deterministic but not under AuroraCluster, so
        # apply_to_children on the cluster does not cover it.
        _log_retention_id = "LogRetentionaae0aa3c5b4d4f87b02d85b201efdd8a"
        NagSuppressions.add_resource_suppressions_by_path(
            stack,
            f"/{stack_name}/{_log_retention_id}/ServiceRole/Resource",
            [
                {
                    "id": "AwsSolutions-IAM4",
                    "reason": "CDK-generated CloudWatch Logs retention Lambda uses the standard AWSLambdaBasicExecutionRole managed policy.",
                    "appliesTo": [
                        "Policy::arn:<AWS::Partition>:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole",
                    ],
                },
            ],
        )
        NagSuppressions.add_resource_suppressions_by_path(
            stack,
            f"/{stack_name}/{_log_retention_id}/ServiceRole/DefaultPolicy/Resource",
            [
                {
                    "id": "AwsSolutions-IAM5",
                    "reason": "CDK-generated CloudWatch Logs retention Lambda requires log:* on * to manage log group retention.",
                    "appliesTo": ["Resource::*"],
                },
                {
                    "id": "HIPAA.Security-IAMNoInlinePolicy",
                    "reason": "Inline policy is generated by CDK for the CloudWatch Logs retention custom resource Lambda.",
                },
            ],
        )

        self.aurora_cluster      = cluster
        self.aurora_admin_secret = admin_secret
        return cluster, admin_secret

    # ── Valkey Serverless ─────────────────────────────────────────────────────

    def create_valkey(
        self,
        vpc: ec2.Vpc,
        valkey_sg: ec2.SecurityGroup,
        kms_key: kms.Key,
    ) -> elasticache.CfnServerlessCache:
        """Create a Valkey (Redis-compatible) Serverless cache.

        Shared across all tenants; tenants are isolated by key-prefix convention
        (e.g. "test-a:" prefix on all OpenEMR session/cache keys).

        Returns:
            The created CfnServerlessCache.

        TODO Sprint 4.5:
            - engine="valkey", major_engine_version="8"
            - ServerlessCacheConfiguration (max_data_storage, max_ecpu_per_second)
            - subnet_ids = vpc private subnets
            - security_group_ids = [valkey_sg.security_group_id]
            - kms_key_id = kms_key.key_id
            - Store endpoint in SSM
        """
        raise NotImplementedError("TODO Sprint 4.5: implement create_valkey()")

    # ── DynamoDB tenant registry ──────────────────────────────────────────────

    def create_tenant_registry(self, kms_key: kms.Key) -> dynamodb.Table:
        """Create the DynamoDB table that tracks all provisioned tenants.

        Schema:
            PK  tenant_id   (string)  — e.g. "acme-health"
            Attributes:    subdomain, plan_tier, created_at, status,
                           fargate_service_arn, db_secret_arn

        Returns:
            The created Table.

        TODO Sprint 4.5:
            - billing_mode=PAY_PER_REQUEST
            - encryption=TableEncryption.CUSTOMER_MANAGED (kms_key)
            - point_in_time_recovery=True
            - removal_policy=RETAIN (never accidentally drop tenant records)
            - Store table name in SSM
        """
        raise NotImplementedError("TODO Sprint 4.5: implement create_tenant_registry()")
